eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-port: 8761
  instance:
    hostname: localhost
    prefer-ip-address: true
